# Generated by Django 2.2.4 on 2019-09-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20170731_2225'),
        ('player', '0002_auto_20190911_1317'),
    ]

    operations = [
    ]
