# Generated by Django 2.2.4 on 2019-09-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0004_auto_20170904_0947'),
        ('gameplay', '0005_auto_20190917_1353'),
    ]

    operations = [
    ]
